[versions]
agp = "8.4.2"
api = "82"


[libraries]
api = { group = "de.robv.android.xposed", name = "api", version.ref = "api" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

